### ISSUE TITLE
data should be editable

### ISSUE THREAD

**Issue by JanUrbanHtw** [JanUrbanHtw/LeafAlone#10]
- [x] User should see the Plant created by AddPlant
- [x] Adding a plant should redirect to PlantList 
- [x] Contributor should see a confirmation Window summarizing the PlantCare object before submitting 
- [x] Contributor should get a Thank you message

- [x] plants should be editable
- [x] message in list when is empty with a link to plants/add

- [x] List for PlantCare Objects
- [x] Option to edit PlantCare

- [x] User should be able to see PlantCare for their plants
- [x] If user is misstreating their plants (wrong sunSituation) it should show in the list

**Comment by cobock** [comment]
- [ ] Option to edit plant should be visible in plant list

**Comment by cobock** [comment]
I will make the PlantCare editable!
